### ISSUE TITLE
this project's docker image can run on windows platform?

### ISSUE THREAD

**Issue by lonngxiang** [scatterlab/faiss-serving#11]

**Comment by lonngxiang** [comment]
terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in faiss::FileIOReader::FileIOReader(const char*) at _deps/faiss-src/faiss/impl/io.cpp:81: Error: 'f' failed: could not open D:/t** for reading: No such file or directory

**Comment by harrydrippin** [comment]
Hello lonngxiang,

We designed our Docker image as platform-agnostic structure, but we didn't tested our image on Windows platform. But we think it will work on Windows too. Can you provide some details about your use case? (Execution parameters, `docker run` settings, etc.)

**Comment by lonngxiang** [comment]
> Hello lonngxiang,
> 
> We designed our Docker image as platform-agnostic structure, but we didn't tested our image on Windows platform. But we think it will work on Windows too. Can you provide some details about your use case? (Execution parameters, `docker run` settings, etc.)

yes,tks for your reply,because there don't have a document,i donot know what do specific parameters mean ;this is my error:
use:
docker run -p 8080:8080 -v /path/to/faiss/index:/path2/to/faiss/index scatterlab/faiss-serving --index-file D:/***ex/tests1.faiss
error:
![image](https://user-images.githubusercontent.com/40717349/114367756-5bffb980-9baf-11eb-81e5-49afaa770930.png)

**Comment by harrydrippin** [comment]
Thank you for providing some detail! Your usage has an error: your are providing your local path to `--index-file` argument, but you are not linking the file to Docker volume. Try below:

```
docker run -p 8080:8080 \
  -v D:/***ex/tests1.faiss:/index.faiss \
  scatterlab/faiss-serving --index-file /index.faiss
```

You need to mount your index file (`D:/***ex/tests1.faiss`) to some where inside the container (`/index.faiss`, on this example) before using the file inside the container.

**Comment by lonngxiang** [comment]
> Thank you for providing some detail! Your usage has an error: your are providing your local path to `--index-file` argument, but you are not linking the file to Docker volume. Try below:
> 
> ```
> docker run -p 8080:8080 \
>   -v D:/***ex/tests1.faiss:/index.faiss \
>   scatterlab/faiss-serving --index-file /index.faiss
> ```
> 
> You need to mount your index file (`D:/***ex/tests1.faiss`) to some where inside the container (`/index.faiss`, on this example) before using the file inside the container.

thank you; now it is working

**Comment by harrydrippin** [comment]
Great to hear that! :) If you don't have any question more, please close this issue.
